package com.xyl.greendao;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig libraryCartBeanDaoConfig;
    private final DaoConfig treasuryCartBeanDaoConfig;
    private final DaoConfig cartDaoConfig;

    private final LibraryCartBeanDao libraryCartBeanDao;
    private final TreasuryCartBeanDao treasuryCartBeanDao;
    private final CartDao cartDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        libraryCartBeanDaoConfig = daoConfigMap.get(LibraryCartBeanDao.class).clone();
        libraryCartBeanDaoConfig.initIdentityScope(type);

        treasuryCartBeanDaoConfig = daoConfigMap.get(TreasuryCartBeanDao.class).clone();
        treasuryCartBeanDaoConfig.initIdentityScope(type);

        cartDaoConfig = daoConfigMap.get(CartDao.class).clone();
        cartDaoConfig.initIdentityScope(type);

        libraryCartBeanDao = new LibraryCartBeanDao(libraryCartBeanDaoConfig, this);
        treasuryCartBeanDao = new TreasuryCartBeanDao(treasuryCartBeanDaoConfig, this);
        cartDao = new CartDao(cartDaoConfig, this);

        registerDao(LibraryCartBean.class, libraryCartBeanDao);
        registerDao(TreasuryCartBean.class, treasuryCartBeanDao);
        registerDao(Cart.class, cartDao);
    }
    
    public void clear() {
        libraryCartBeanDaoConfig.clearIdentityScope();
        treasuryCartBeanDaoConfig.clearIdentityScope();
        cartDaoConfig.clearIdentityScope();
    }

    public LibraryCartBeanDao getLibraryCartBeanDao() {
        return libraryCartBeanDao;
    }

    public TreasuryCartBeanDao getTreasuryCartBeanDao() {
        return treasuryCartBeanDao;
    }

    public CartDao getCartDao() {
        return cartDao;
    }

}
